// Generated by view binder compiler. Do not edit!
package vcmsa.projects.expensetracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import vcmsa.projects.expensetracker.R;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final Button btnManageCategories;

  @NonNull
  public final Button btnSpendingGoals;

  @NonNull
  public final Button btnViewGraphs;

  @NonNull
  public final FloatingActionButton fabAddExpense;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final RecyclerView recyclerViewExpenses;

  @NonNull
  public final TextView textViewTotalAmount;

  @NonNull
  public final Toolbar toolbar;

  private ActivityMainBinding(@NonNull CoordinatorLayout rootView,
      @NonNull Button btnManageCategories, @NonNull Button btnSpendingGoals,
      @NonNull Button btnViewGraphs, @NonNull FloatingActionButton fabAddExpense,
      @NonNull ProgressBar progressBar, @NonNull RecyclerView recyclerViewExpenses,
      @NonNull TextView textViewTotalAmount, @NonNull Toolbar toolbar) {
    this.rootView = rootView;
    this.btnManageCategories = btnManageCategories;
    this.btnSpendingGoals = btnSpendingGoals;
    this.btnViewGraphs = btnViewGraphs;
    this.fabAddExpense = fabAddExpense;
    this.progressBar = progressBar;
    this.recyclerViewExpenses = recyclerViewExpenses;
    this.textViewTotalAmount = textViewTotalAmount;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnManageCategories;
      Button btnManageCategories = ViewBindings.findChildViewById(rootView, id);
      if (btnManageCategories == null) {
        break missingId;
      }

      id = R.id.btnSpendingGoals;
      Button btnSpendingGoals = ViewBindings.findChildViewById(rootView, id);
      if (btnSpendingGoals == null) {
        break missingId;
      }

      id = R.id.btnViewGraphs;
      Button btnViewGraphs = ViewBindings.findChildViewById(rootView, id);
      if (btnViewGraphs == null) {
        break missingId;
      }

      id = R.id.fabAddExpense;
      FloatingActionButton fabAddExpense = ViewBindings.findChildViewById(rootView, id);
      if (fabAddExpense == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.recyclerViewExpenses;
      RecyclerView recyclerViewExpenses = ViewBindings.findChildViewById(rootView, id);
      if (recyclerViewExpenses == null) {
        break missingId;
      }

      id = R.id.textViewTotalAmount;
      TextView textViewTotalAmount = ViewBindings.findChildViewById(rootView, id);
      if (textViewTotalAmount == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new ActivityMainBinding((CoordinatorLayout) rootView, btnManageCategories,
          btnSpendingGoals, btnViewGraphs, fabAddExpense, progressBar, recyclerViewExpenses,
          textViewTotalAmount, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
