// Generated by view binder compiler. Do not edit!
package vcmsa.projects.expensetracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import vcmsa.projects.expensetracker.R;

public final class ActivityAddExpenseBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button btnSaveExpense;

  @NonNull
  public final Button btnSelectDate;

  @NonNull
  public final TextInputEditText editTextAmount;

  @NonNull
  public final TextInputEditText editTextDescription;

  @NonNull
  public final TextInputEditText editTextTitle;

  @NonNull
  public final Spinner spinnerCategory;

  @NonNull
  public final TextView textViewSelectedDate;

  @NonNull
  public final Toolbar toolbar;

  private ActivityAddExpenseBinding(@NonNull LinearLayout rootView, @NonNull Button btnSaveExpense,
      @NonNull Button btnSelectDate, @NonNull TextInputEditText editTextAmount,
      @NonNull TextInputEditText editTextDescription, @NonNull TextInputEditText editTextTitle,
      @NonNull Spinner spinnerCategory, @NonNull TextView textViewSelectedDate,
      @NonNull Toolbar toolbar) {
    this.rootView = rootView;
    this.btnSaveExpense = btnSaveExpense;
    this.btnSelectDate = btnSelectDate;
    this.editTextAmount = editTextAmount;
    this.editTextDescription = editTextDescription;
    this.editTextTitle = editTextTitle;
    this.spinnerCategory = spinnerCategory;
    this.textViewSelectedDate = textViewSelectedDate;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAddExpenseBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAddExpenseBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_add_expense, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAddExpenseBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnSaveExpense;
      Button btnSaveExpense = ViewBindings.findChildViewById(rootView, id);
      if (btnSaveExpense == null) {
        break missingId;
      }

      id = R.id.btnSelectDate;
      Button btnSelectDate = ViewBindings.findChildViewById(rootView, id);
      if (btnSelectDate == null) {
        break missingId;
      }

      id = R.id.editTextAmount;
      TextInputEditText editTextAmount = ViewBindings.findChildViewById(rootView, id);
      if (editTextAmount == null) {
        break missingId;
      }

      id = R.id.editTextDescription;
      TextInputEditText editTextDescription = ViewBindings.findChildViewById(rootView, id);
      if (editTextDescription == null) {
        break missingId;
      }

      id = R.id.editTextTitle;
      TextInputEditText editTextTitle = ViewBindings.findChildViewById(rootView, id);
      if (editTextTitle == null) {
        break missingId;
      }

      id = R.id.spinnerCategory;
      Spinner spinnerCategory = ViewBindings.findChildViewById(rootView, id);
      if (spinnerCategory == null) {
        break missingId;
      }

      id = R.id.textViewSelectedDate;
      TextView textViewSelectedDate = ViewBindings.findChildViewById(rootView, id);
      if (textViewSelectedDate == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new ActivityAddExpenseBinding((LinearLayout) rootView, btnSaveExpense, btnSelectDate,
          editTextAmount, editTextDescription, editTextTitle, spinnerCategory, textViewSelectedDate,
          toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}


//🔗 Android Developer Portal  
//   https://developer.android.com  
//   (Official documentation, API guides, and Jetpack libraries)
//
//🔗 Android Studio User Guide  
//   https://developer.android.com/studio/intro  
//   (Installation, setup, Gradle, and emulator instructions)
//
//🔗 Android Codelabs  
//   https://developer.android.com/codelabs  
//   (Hands-on tutorials for Room, ViewModel, Compose, etc.)
//
//🔗 Android API Reference  
//   https://developer.android.com/reference  
//   (Full SDK API list for Java & Kotlin)
//
//🔗 Stack Overflow - Android  
//   https://stackoverflow.com/questions/tagged/android  
//   (Community Q&A, error troubleshooting)
//
//🔗 Android GitHub Samples  
//   https://github.com/android  
//   (Official sample projects for Android features)
//
//🔗 Kotlin Playground  
//   https://play.kotlinlang.org  
//   (Practice Kotlin syntax online)
//
//🔗 JetBrains Academy  
//   https://www.jetbrains.com/academy/  
//   (Courses for Kotlin, Java, Android development)



