// Generated by view binder compiler. Do not edit!
package vcmsa.projects.expensetracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.navigation.NavigationView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import vcmsa.projects.expensetracker.R;

public final class ActivityMain2Binding implements ViewBinding {
  @NonNull
  private final DrawerLayout rootView;

  @NonNull
  public final AppBarMainBinding appBarMain;

  @NonNull
  public final DrawerLayout drawerLayout;

  @NonNull
  public final NavigationView navView;

  private ActivityMain2Binding(@NonNull DrawerLayout rootView,
      @NonNull AppBarMainBinding appBarMain, @NonNull DrawerLayout drawerLayout,
      @NonNull NavigationView navView) {
    this.rootView = rootView;
    this.appBarMain = appBarMain;
    this.drawerLayout = drawerLayout;
    this.navView = navView;
  }

  @Override
  @NonNull
  public DrawerLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMain2Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMain2Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main2, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMain2Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.app_bar_main;
      View appBarMain = ViewBindings.findChildViewById(rootView, id);
      if (appBarMain == null) {
        break missingId;
      }
      AppBarMainBinding binding_appBarMain = AppBarMainBinding.bind(appBarMain);

      DrawerLayout drawerLayout = (DrawerLayout) rootView;

      id = R.id.nav_view;
      NavigationView navView = ViewBindings.findChildViewById(rootView, id);
      if (navView == null) {
        break missingId;
      }

      return new ActivityMain2Binding((DrawerLayout) rootView, binding_appBarMain, drawerLayout,
          navView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
//🔗 Android Developer Portal  
//   https://developer.android.com  
//   (Official documentation, API guides, and Jetpack libraries)
//
//🔗 Android Studio User Guide  
//   https://developer.android.com/studio/intro  
//   (Installation, setup, Gradle, and emulator instructions)
//
//🔗 Android Codelabs  
//   https://developer.android.com/codelabs  
//   (Hands-on tutorials for Room, ViewModel, Compose, etc.)
//
//🔗 Android API Reference  
//   https://developer.android.com/reference  
//   (Full SDK API list for Java & Kotlin)
//
//🔗 Stack Overflow - Android  
//   https://stackoverflow.com/questions/tagged/android  
//   (Community Q&A, error troubleshooting)
//
//🔗 Android GitHub Samples  
//   https://github.com/android  
//   (Official sample projects for Android features)
//
//🔗 Kotlin Playground  
//   https://play.kotlinlang.org  
//   (Practice Kotlin syntax online)
//
//🔗 JetBrains Academy  
//   https://www.jetbrains.com/academy/  
//   (Courses for Kotlin, Java, Android development)


